// EntryCard Styles - Shared design tokens for the EntryCard component
import { colors, fonts } from "../../lib/theme.js";

export const styles = {
  card: {
    backgroundColor: colors.surface,
    border: `1px solid ${colors.border}`,
    borderRadius: 12,
    padding: 28,
    marginBottom: 24,
  },
  header: {
    marginBottom: 20,
  },
  termKhmer: {
    fontFamily: fonts.khmer,
    fontSize: 42,
    fontWeight: 700,
    color: colors.gold,
    margin: 0,
    lineHeight: 1.1,
  },
  termMeta: {
    display: "flex",
    alignItems: "baseline",
    gap: 12,
    marginTop: 6,
  },
  romanized: {
    fontFamily: fonts.sans,
    fontSize: 20,
    color: colors.emerald,
    fontWeight: 600,
  },
  pronunciation: {
    fontFamily: fonts.mono,
    fontSize: 14,
    color: colors.muted,
  },
  categoryBadge: {
    display: "inline-block",
    marginTop: 12,
    padding: "4px 12px",
    backgroundColor: "rgba(46, 230, 168, 0.12)",
    color: colors.emerald,
    border: `1px solid ${colors.emeraldDeep}`,
    borderRadius: 999,
    fontSize: 12,
    fontFamily: fonts.mono,
    letterSpacing: 0.5,
  },
  facts: {
    display: "grid",
    gridTemplateColumns: "auto 1fr",
    gap: "12px 16px",
    margin: "0 0 20px",
    padding: 0,
  },
  fact: {
    margin: 0,
  },
  factLabel: {
    fontFamily: fonts.mono,
    fontSize: 11,
    color: colors.muted,
    textTransform: "uppercase",
    letterSpacing: 0.8,
    margin: 0,
  },
  factValue: {
    fontSize: 15,
    color: colors.text,
    margin: "4px 0 0",
    paddingLeft: 10,
    borderLeft: `1px solid ${colors.border}`,
  },
  usageNotes: {
    fontSize: 15,
    lineHeight: 1.6,
    color: colors.text,
    margin: "0 0 20px",
  },
  genExplorer: {
    margin: "0 0 20px",
    padding: "18px 20px",
    backgroundColor: colors.surfaceAlt,
    borderRadius: 6,
    borderLeft: `3px solid ${colors.gold}`,
  },
  genExplorerLabel: {
    fontFamily: fonts.mono,
    fontSize: 11,
    color: colors.gold,
    textTransform: "uppercase",
    letterSpacing: 0.8,
    margin: "0 0 12px",
  },
  genTabs: {
    display: "flex",
    gap: 8,
    marginBottom: 16,
  },
  genTab: {
    fontFamily: fonts.sans,
    fontSize: 13,
    padding: "6px 12px",
    borderRadius: 999,
    border: `1px solid ${colors.border}`,
    backgroundColor: "transparent",
    color: colors.muted,
    cursor: "pointer",
  },
 genTabActive: {
    border: `1px solid ${colors.gold}`,
    color: colors.gold,
    backgroundColor: "rgba(212, 175, 55, 0.1)",
  },
  genPanel: {
    transition: "opacity 200ms ease, transform 200ms ease",
  },
  genStatusRow: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    marginBottom: 10,
  },
  genStatusTrack: {
    flex: 1,
    height: 6,
    borderRadius: 999,
    backgroundColor: colors.border,
    overflow: "hidden",
  },
  genStatusFill: {
    height: "100%",
    borderRadius: 999,
    transition: "width 200ms ease, background-color 200ms ease",
  },
  genStatusLabel: {
    fontFamily: fonts.mono,
    fontSize: 12,
    letterSpacing: 0.5,
    whiteSpace: "nowrap",
  },
  genAlternate: {
    fontSize: 14,
    color: colors.goldSoft,
    margin: "0 0 8px",
  },
  genNoteText: {
    fontSize: 15,
    lineHeight: 1.6,
    color: colors.text,
    margin: "0 0 8px",
    fontStyle: "italic",
  },
  genSource: {
    fontSize: 13,
    color: colors.muted,
    margin: 0,
  },
  example: {
    margin: "0 0 20px",
    padding: "14px 18px",
    backgroundColor: colors.surfaceAlt,
    borderRadius: 6,
  },
  exampleKhmer: {
    fontFamily: fonts.khmer,
    fontSize: 18,
    color: colors.goldSoft,
    margin: 0,
  },
  exampleTrans: {
    fontSize: 14,
    color: colors.muted,
    margin: "6px 0 0",
    fontStyle: "italic",
  },
  tags: {
    display: "flex",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 20,
  },
  tag: {
    padding: "3px 10px",
    backgroundColor: "rgba(212, 175, 55, 0.12)",
    color: colors.goldSoft,
    border: `1px solid ${colors.border}`,
    borderRadius: 4,
    fontSize: 12,
    fontFamily: fonts.mono,
  },
  photoFigure: {
    margin: "0 0 20px",
  },
  photoImage: {
    width: "100%",
    maxHeight: 280,
    objectFit: "cover",
    borderRadius: 8,
    display: "block",
    border: `1px solid ${colors.border}`,
  },
  photoCaption: {
    fontSize: 13,
    color: colors.muted,
    marginTop: 8,
    fontStyle: "italic",
  },
  highlightMark: {
    backgroundColor: colors.gold,
    color: colors.surface,
    padding: "0 3px",
    borderRadius: 3,
    fontWeight: 700,
  },
};